name: 'AWS Pipeline Factory Triggers'
description: 'Integrates github repository to Pipeline Factory'
author: 'AbdoNile @stage-tech'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    default: 'World'
outputs:
  call_payload: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
